mkdir -p -- "$HOME/.vim"
mkdir -p -- "$HOME/.vim-tmp"
cp .bashrc "$HOME/.bashrc"
cp .bash_aliases "$HOME/.bash_aliases"
cp .vimrc "$HOME/.vimrc"
cp -R templates "$HOME/.vim/"
cp .zshrc "$HOME/.zshrc"
cp .p10k.zsh "$HOME/.p10k.zsh"
